/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fldCrowndsaleSol from "./FLDCrowndsale.sol";
export type { fldCrowndsaleSol };
export type { Floppy } from "./Floppy";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
